### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by vardansafaryantoptal** [giddyinc/doctopus#23]
documentation link is broken, is there any additional source I can investigate?
![image](https://user-images.githubusercontent.com/67322153/85820041-72ef2f80-b786-11ea-898e-da506dea2a90.png)

**Comment by blugavere** [comment]
sorry for the broken doc link - removed it

don't have a replacement just yet, but here is a blog post on how to get started

https://medium.com/@benlugavere/documenting-your-node-js-api-painlessly-with-swagger-doctopus-3cf40024037

there's also a working example in the repo

https://github.com/giddyinc/doctopus/blob/master/examples/typescript/src/app.ts#L12
